# Generated by Django 2.0.2 on 2018-09-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tipo Documento de Identidad',
                'verbose_name_plural': 'Tipos Documento de Identidad',
                'ordering': ['codigo', 'descripcion', 'fecha_creacion', 'fecha_edicion'],
            },
        ),
    ]
