# Generated by Django 2.0.2 on 2018-09-16 16:03

import apps.admitidos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('anio', models.CharField(default=apps.admitidos.models.Admitido.anio_actual, editable=False, max_length=4, verbose_name='Año')),
                ('periodo', models.CharField(default=apps.admitidos.models.Admitido.periodo_actual, editable=False, max_length=2, verbose_name='Período')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programas.Programa', verbose_name='Programa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.TipoDocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Admitido',
                'verbose_name_plural': 'Admitidos',
                'ordering': ['programa', 'tipo_documento', 'primer_apellido', 'segundo_apellido', 'primer_nombre', 'segundo_nombre'],
            },
        ),
    ]
