# Generated by Django 2.0.2 on 2018-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitido',
            name='jornada',
            field=models.CharField(choices=[('1', 'Jornada Tarde - 2pm a 6pm'), ('2', 'Jornada Nocturna - 6pm a 10pm')], max_length=5, null=True, verbose_name='Jornada'),
        ),
    ]
