# Generated by Django 2.0.2 on 2018-09-16 22:32

import apps.gestion_documental.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admitidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Documento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Documento Requerido de Admitidos',
                'verbose_name_plural': 'Documentos Requeridos de Admitidos',
                'ordering': ['descripcion', 'fecha_creacion', 'fecha_edicion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdmitido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='admitidos/', verbose_name='Documento')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('admitido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admitidos.Admitido', verbose_name='Admitido')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_documental.Documento', verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Documento Radicado de Admitidos',
                'verbose_name_plural': 'Documentos Radicados de Admitidos',
                'ordering': ['admitido', 'fecha_creacion', 'fecha_edicion'],
            },
        ),
    ]
