# Generated by Django 2.0.2 on 2018-09-17 03:02

import apps.gestion_documental.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['descripcion', 'fecha_creacion', 'fecha_edicion'], 'verbose_name': 'Documento Requerido', 'verbose_name_plural': 'Documentación Requerida'},
        ),
        migrations.AlterField(
            model_name='documentoadmitido',
            name='archivo',
            field=models.FileField(upload_to=apps.gestion_documental.models.custom_upload_to, verbose_name='Documento'),
        ),
    ]
